#!/bin/bash
# Quick start guide - System konfiguracji YAML

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║  ✅ System konfiguracji YAML jest gotowy!                        ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 Co otrzymasz w nowym eksperymencie:"
echo "   ✓ config_loader.py - moduł konfiguracji"
echo "   ✓ configs/*.yaml - pliki konfiguracyjne (base, preview, smoke, train)"
echo "   ✓ experiment.py - z integracją konfiguracji"
echo "   ✓ run.py - z obsługą CLI"
echo "   ✓ Dokumentacja - CONFIG_README.md"
echo ""
echo "🚀 Szybki start:"
echo ""
echo "1. Wygeneruj nowy eksperyment:"
echo "   $ python new_experiment.py E002-01 my-experiment"
echo ""
echo "2. [Opcjonalnie] Dostosuj konfigurację:"
echo "   $ cd e002-01-my-experiment"
echo "   $ vim dataset/src/configs/base.yaml"
echo "   $ vim dataset/src/config_loader.py  # dodaj własne pola do RunConfig"
echo ""
echo "3. Zaimplementuj experiment.py (konfiguracja już zintegrowana!)"
echo ""
echo "4. Uruchom:"
echo "   Notebook: train(\"preview\")"
echo "   CLI:      python run.py --profile train"
echo ""
echo "📚 Dokumentacja:"
echo "   - templates/experiment/CONFIG_README.md - szybki start"
echo "   - e001-01-wavelets-baseline/CONFIG_SYSTEM.md - pełna dokumentacja"
echo "   - SUMMARY.md - podsumowanie"
echo ""
echo "✅ Testy:"
echo "   $ python test_template.py  # test szablonu"
echo "   $ cd e001-01-wavelets-baseline && python test_config.py  # testy systemu"
echo "   $ cd e001-01-wavelets-baseline && python demo_config.py  # demo"
echo ""
echo "🎯 Profile dostępne out-of-the-box:"
echo "   - preview: 200 kroków, live mode, bez W&B"
echo "   - smoke:   500 kroków, test pipeline"
echo "   - train:   5k kroków, pełny trening"
echo ""
echo "🎉 Gotowe! Możesz zacząć generować nowe eksperymenty!"
echo ""
